name: Update table when modified or added
on:
  push:
    branches:
    - master
jobs:
  get_changes:
    runs-on: ubuntu-latest
    steps:

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: File Changes
        run: |
          cp $HOME/files.json files.json

      - name: Upload Changes
        uses: actions/upload-artifact@v2
        with:
          name: push-changes
          path: files.json
  
  to_cloud_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/google-github-actions/setup-gcloud/blob/master/setup-gcloud/README.md
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_MAIN_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_TASK_CALLER }}
          export_default_credentials: true

      - name: Download changes
        uses: actions/download-artifact@v2
        with:
          name: push-changes

      - name: Add to Cloud Task
        uses: ./.github/workflows/add-to-cloudtask
        with:
          project_id: ${{ secrets.GCP_MAIN_PROJECT_ID }}
          location: ${{ secrets.GCP_LOCATION }}
          queue: ${{ secrets.GCP_ONECLICK_QUEUE }}
          taskurl: ${{ secrets.GCP_ONECLICK_URL }}
          service_account: ${{ secrets.GCP_ONECLICK_EMAIL }}
          

