name: "Setup Environment"
description: "Create config files and credentials needed to run basedosdados client"
author: "Base dos Dados"

runs: 
  using: composite
  steps:
    - run: pip install --upgrade -r ${{ github.workspace }}/python-package/requirements-dev.txt 
      shell: bash
    - run: echo "=============================******************list******************============================="
      shell: bash
    - run: ls -al /home/runner/work/mais/mais
      shell: bash
    - run: python ${{ github.workspace }}/python-package/setup.py develop
      shell: bash
    - run: basedosdados --help
      shell: bash
    - run: python  ${{ github.action_path }}/main.py
      shell: bash
    - run: pytest
      shell: bash