name: "Setup Environment"
description: "Create config files and credentials needed to run basedosdados client"
author: "Base dos Dados"

runs: 
  using: composite
  steps:
    - run: echo "=============================******************requirements-dev.txt******************============================="
      shell: bash
    - run: cd ${{ github.workspace }}
      shell: bash
    - run: pip install --upgrade -r python-package/requirements-dev.txt 
      shell: bash
    - run: echo "=============================******************list files******************============================="
      shell: bash
    - run: ls -al
      shell: bash
    - run: echo "=============================******************setup.py******************============================="
      shell: bash
    - run: cd ${{ github.workspace }}
      shell: bash
    - run: python python-package/setup.py develop
      shell: bash
    - run: basedosdados --help
      shell: bash
    - run: python  ${{ github.action_path }}/main.py
      shell: bash
    - run: pytest
      shell: bash